config/routes.rb
Rails.application.routes.draw do
  get 'recipes/public_recipes'
  resources :recipes do
    resources :recipes_foods
  end
  resources :foods
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "landing_page#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :destroy, Food do |food|
      food.user == user
    end

    can :update, Recipe do |recipe|
      recipe.user == user
    end

    can :update, RecipesFood do |recipe_food|
      recipe_food.user == user
    end

    can :destroy, Recipe do |recipe|
      recipe.user == user
    end

    can :create, Food
    can :create, Recipe
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/models/recipes_food.rb
class RecipesFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  has_one :user, through: :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :recipes_foods, through: :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email username password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.order('id DESC')
  end

  def new
    newfood = Food.new
    respond_to do |format|
      format.html { render :new, locals: { newfood: } }
    end
  end

  def create
    @food = current_user.foods.new(food_params)
    respond_to do |format|
      format.html do
        if @food.save
          redirect_to foods_path
        else
          newfood = Food.new
          render :new, locals: { newfood: }
        end
      end
    end
  end

  def destroy
    Food.destroy(params[:id])
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipes_foods).where(public: 't').order('id DESC')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes.includes(:recipes_foods).all.order('id DESC')
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = current_user.foods
    @food_items = []
    @foods.each do |food|
      @food_items << [food.name, food.id]
    end
    @food_items
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: 't').order('id DESC')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
  def index
    @foods = current_user.recipes_foods.select(:food_id, 'SUM(quantity) as quantity').group(:food_id, :quantity)
    @sum = 0
    @foods.each do |food|
      @sum += food.quantity * food.food.price
    end
  end

  def create
    @recipes_foods = RecipesFood.where('food_id = :x and recipe_id = :y',
                                       x: recipes_foods_params[:food_id], y: recipes_foods_params[:recipe_id])

    if @recipes_foods.size.zero?
      @recipes_foods = RecipesFood.new(recipes_foods_params)
    else
      @recipes_foods.update(recipes_foods_params)
      redirect_to recipe_url(@recipes_foods[0].recipe) and return
    end

    respond_to do |format|
      if @recipes_foods.save
        format.html { redirect_to recipe_url(@recipes_foods.recipe), notice: 'Ingredient was successfully saved.' }
        format.json { render :show, status: :created, location: @recipes_foods.recipe }
      else
        format.html { redirect_to new_recipe_recipes_food_url, notice: 'Ingredient was not successfully saved.' }
        format.json { render json: @recipes_foods.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @foods = current_user.foods
    @food_items = []
    @foods.each do |food|
      @food_items << [food.name, food.id]
    end
    @recipe = current_user.recipes.find(params[:recipe_id])
  end

  def show; end

  def edit
    @recipe_food = RecipesFood.find(params[:id])
  end

  def update
    @recipe_food = RecipesFood.find(params[:id])
    if @recipe_food.update(recipes_foods_params)
      flash[:succes] = 'Recipe food updated successfully'
      redirect_to recipe_path(@recipe_food.recipe)
    else
      flash[:error] = 'Recipe food update failed'
      render :edit
    end
  end

  def destroy
    RecipesFood.destroy(params[:id])
    redirect_to recipe_path(recipes_foods_params[:recipe_id])
  end

  # Only allow a list of trusted parameters through.
  def recipes_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity, :recipe_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="container mt-5 pt-4">
  <div class="card">
    <div class="card-header text-center">
      <h3>Food List</h3>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-12 d-flex justify-content-end my-3">
          <%= link_to "Add Food", new_food_path() ,class: "btn btn-primary" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 mx-auto">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th scope="col">Food</th>
                <th scope="col">Quantity</th>
                <th scope="col">Measurement Unit</th>
                <th scope="col">Unit Price</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @foods.each do |food| %>
                <tr>
                  <td><%= food.name %></td>
                  <td><%= food.quantity %></td>
                  <td><%= food.measurement_unit %></td>
                  <td><%= food.price %></td>
                  <td>
                    <% if can? :destroy, food %>
                      <%= form_with url: food_path(food.id), method: :delete do |f| %>
                        <%= f.submit 'Delete', class: "text-danger" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted text-center">
      “You do not need a silver fork to eat good food.” ~ By Paul Prudhomme
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container mt-5 pb-2 pt-5">
  <div class="card">
    <div class="card-header text-center">
      <h3>Add Food</h3>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-6 mx-auto">
          <% if flash[:error] %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
          <% end %>
          <%= form_with model: newfood, url: foods_path, method: :post, local: true, scope: :food do |f| %>
            <div>
              <div>
                <%= f.label :name, class: "form-label fw-bold", style: "display: block"  %> <br/>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="mb-3">
                <div>
                  <%= f.label :measurement_unit, class: "form-label fw-bold", style: "display: block"  %> <br/>
                  <%= f.text_field :measurement_unit, class: "form-control" %>
                </div>
              </div>
              <div class="mb-3">
                <div>
                  <%= f.label :price, class: "form-label fw-bold", style: "display: block"  %> <br/>
                  <%= f.text_field :price, class: "form-control" %>
                </div>
              </div>
              <div class="mb-3">
                <div>
                  <%= f.label :quantity, class: "form-label fw-bold", style: "display: block"  %> <br/>
                  <%= f.number_field :quantity, class: "form-control" %>
                </div>
              </div>
              <div class = "mb-3">
                <%= f.submit "Add Food", class: "btn btn-success w-100" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted text-center">
      “You do not need a silver fork to eat good food.” ~ By Paul Prudhomme
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<h1> Single post view </h1>

app/views/landing_page/_header.html.erb
 <!-- Masthead-->
<header class="masthead">
  <div class="container-fluid px-0">
    <h3 class="">
      <% if current_user %>
        <%= "Hi, #{current_user.name.split(' ')[0]} !!" %>
      <% end %>
    </h3>
    <div class="masthead-subheading">Welcome To Our Recipe Corner!</div>
        <div class="masthead-heading text-uppercase">Let's make our kitchen magnificent</div>
        <% if current_user.nil? %>    
          <%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-xl text-uppercase"  %>
        <% else %>
          <%= link_to "Add food", new_food_path, class: "btn btn-primary btn-xl"  %>
          <%= link_to "Add recipe", new_recipe_path, class: "btn btn-primary btn-xl"  %>
        <% end %>
        </div>
    </div>
  </div>
</header>

app/views/landing_page/_list.html.erb
<div class="container pt-4 pb-4">
<% @recipes.each do |recipe| %>  
<div class="card mb-4">
    <div class="card-body">
      <div class="container">
        <div class="row bg-light p-3">
          <div class="col-6">
            <div class="card">
              <div class="card-header">
                <%= recipe.name %>
              </div>
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <footer class="blockquote-footer"><%= "By #{recipe.user.name}" %></footer>
                </blockquote>
                <div class="mt-2">
                  <%= link_to 'Show this recipe', recipe_path(recipe.id) %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Total food item: <%= recipe.recipes_foods.size %></li>
                <li class="list-group-item">
                <% sum = 0 %>
                <% recipe.recipes_foods.each do |food| %>
                  <% sum += food.quantity * food.food.price %>
                <% end %>
                <%= "Total price: $#{sum}" %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/landing_page/index.html.erb
<%= render 'landing_page/header'%>
<%= render 'landing_page/list'%>

app/views/layouts/_footer.html.erb
<footer class="text-center bg-dark">
    <div class="container text-white py-4 py-lg-5">
        <ul class="list-inline">
            <li class="list-inline-item me-4"><a class="link-light" href="#">Designed</a></li>
            <li class="list-inline-item me-4"><a class="link-light" href="#">by</a></li>
            <li class="list-inline-item me-4"><a class="link-light" href="#">Felix &amp; Edward</a></li>
        </ul>
        <ul class="list-inline">
            <li class="list-inline-item me-4"><svg class="bi bi-github text-light" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                </svg></li>
            <li class="list-inline-item me-4"><svg class="bi bi-twitter text-light" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                </svg></li>
            <li class="list-inline-item"><svg class="bi bi-linkedin text-light" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                </svg></li>
        </ul>
        <p class="text-muted mb-0">Copyright © 2022 F&amp;E</p>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav id="mainNav" class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container">
   <%= link_to 'F&E Recipe App', root_path, class: 'navbar-brand' %>
   <button class="navbar-toggler navbar-toggler-right" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
    <div id="navbarResponsive" class="collapse navbar-collapse">
    <ul class="navbar-nav ms-auto">
      <% if current_user.nil? %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Recipes', recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Public Recipes', recipes_public_recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
</div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <script src="https://kit.fontawesome.com/46794738cc.js" crossorigin="anonymous"></script>
  </head>
  <div class="container-fluid px-0">
    <body>
      <%= render 'layouts/nav'%>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </body>
  </div>
</html>

app/views/recipes/_add_food.html.erb
<div class="container">
<div class="card">
  <div class="card-header">
    Recipe Details
  </div>
  <div class="card-body justify-content-start">
    <table class="table table-sm table-striped text-left">
      <tr>
        <td>Food</td>
        <td>Quantity</td>
        <td>Price</td>
        
        <td>Actions</td>
      </tr>
      <% recipe.recipes_foods.each do |food_item| %>
        <tr>
          <td><%= food_item.food.name %></td>
          <td><%= "#{food_item.quantity} #{food_item.food.measurement_unit}" %></td>
          <td><%= "$#{ food_item.quantity * food_item.food.price}" %></td>
          <td class="d-flex">
          <% if can? :update, food_item %>
           <%= link_to 'Modify', edit_recipe_recipes_food_path(recipe.id, food_item.id), method: :patch, class: 'btn btn-sm btn-primary' %>
          <% end %>

           <% if can? :destroy, food_item.food %>
             <%= form_with url: recipe_recipes_food_path(recipe.id, food_item.id), method: :delete, local: true, scope: :recipe_food do |f| %>
               <%= f.hidden_field :recipe_id, {value: recipe.id} %>
               <%= f.hidden_field :quantity, {value: food_item.quantity} %>
               <%= f.hidden_field :food_id, {value: food_item.food_id} %>
               <%= f.submit 'Delete', class: 'mx-2' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="card-footer text-muted">
    ~Great Food!!~
  </div>
</div>
</div>

app/views/recipes/_add_modal.html.erb
<div class="container d-flex justify-content-end">
</div>

<div class="container my-4">
<div class="row mb-3">
<div class="col-md-9">
  <%= link_to 'General shopping list', recipe_recipes_foods_path(recipe.id), class: 'btn btn-primary' %>
</div>

<div class="col-md-3 d-flex justify-content-end">
 <div>
 <%= link_to 'Add Ingredient', new_recipe_recipes_food_path(recipe.id), class: 'btn btn-primary' %>
 </div>

</div>
</div>
</div>
</div>

app/views/recipes/_recipe.html.erb
<div class="container mt-4 pt-3 pb-3">
  <div class="row bg-light">
    <div class="col-sm-3 p-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-text"><%= recipe.name %></h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item text-success px-0"><strong>Preparation time:</strong> <%= recipe.preparation_time %>mins</li>
            <li class="list-group-item text-success px-0"><strong>Cooking time:</strong> <%= recipe.cooking_time %> hr</li>
          </ul>
          <% if can? :destroy, recipe %>
            <%= button_to "Remove", @recipe, method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-9 p-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Description</h5>
          <p class="card-text"><%= recipe.description %></p>
          <%= link_to "Show this recipe", recipe %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container mt-5 pb-2 pt-5">
  <div class="card">
    <div class="card-header text-center">
      <h3>Editing Recipe</h3>
    </div>
    <div class="card-body">
      <%# <h1></h1> %>
      <div class="row">
        <div class="col-sm-6 mx-auto">
          <%= render "form", recipe: @recipe %>
          <br>
          <div>
            <%= link_to "Show this recipe", @recipe, class: "text-decoration-none" %> |
            <span><%= link_to "", recipes_path, class: "fas fa-arrow-left fa-lg text-decoration-none" %></span>
            <span><%= link_to "Back to Recipes", recipes_path, class: "text-decoration-none" %></span>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted text-center">
      “You do not need a silver fork to eat good food.” ~ By Paul Prudhomme
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container my-5" id="recipes">
 <div class="d-flex justify-content-end">
   <%= link_to "+ New recipe", new_recipe_path, class: 'btn btn-primary' %>
 </div>
</div>
<div>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container mt-5 pb-2 pt-5">
  <div class="card">
    <div class="card-header text-center">
      <h3>Add New Recipe</h3>
    </div>
    <div class="card-body">
      <%# <h1></h1> %>
      <div class="row">
        <div class="col-sm-6 mx-auto">
          <%= render "form", recipe: @recipe %>
          <br>
          <div>
            <span><%= link_to "", recipes_path, class: "fas fa-arrow-left fa-lg text-decoration-none" %></span>
            <span><%= link_to "Back to Recipes", recipes_path, class: "text-decoration-none" %></span>
            
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted text-center">
      “You do not need a silver fork to eat good food.” ~ By Paul Prudhomme
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'description', recipe: @recipe %>

<% if can? :update, @recipe %>
  <%= render "add_modal", recipe: @recipe %>
<% end %>

<%= render "add_food", recipe: @recipe %>


<div class="container d-flex justify-content-between my-5">
 <div>
  <% if can? :update, @recipe %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> 
  | <% end %>
  <%= link_to "Back to recipes", recipes_path %>
 </div>
 <div>
  <% if can? :destroy, @recipe %>
    <%= button_to "Destroy this recipe", @recipe, method: :delete %>
  <% end %>
  </div>
</div>

app/views/recipes_foods/_form.html.erb
<div class="mt-2">
<%= form_with url: recipe_recipes_foods_path, method: :post, local: true, scope: :recipe_food do |f| %>
  <div class="form-group">
    <%= f.select :food_id, options_for_select(@food_items), {}, { :class => 'form-select mb-3' } %>
  </div>

  <div class="form-group">
  <%= f.hidden_field :recipe_id, {value: @recipe.id} %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: 'form-control mb-3' %>
  </div>
  <div>
    <%= f.submit :add, class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>
</div>

app/views/recipes_foods/new.html.erb
<div class="container my-4">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>